{
 "title": "Nutanix",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "VMS  per Node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nutanix_host_count_vms", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Host Read/Write IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nutanix_host_num_read_iops", "legendFormat": "{{hostname}}" },
    { "expr": "nutanix_host_write_io_ppm", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Node CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nutanix_host_hypervisor_cpu_usage_ppm",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nutanix_host_hypervisor_memory_usage_ppm",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Cluster Storage free Gigabyte",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nutanix_cluster_storage_free_bytes/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Compression Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nutanix_cluster_data_reduction_compression_post_reduction_bytes",
     "legendFormat": "Post Reduction"
    },
    {
     "expr": "nutanix_cluster_data_reduction_compression_pre_reduction_bytes",
     "legendFormat": "Pre Reduction"
    },
    {
     "expr": "nutanix_cluster_data_reduction_compression_saving_ratio_ppm",
     "legendFormat": "Saving Ratio"
    }
   ]
  }
 ]
}